[workspace]
resolver = "2"

members = [
    "libraries/axum-jwks",
    "binaries/rave-app-backend",
    "crates/rave-api",
    "crates/rave-api-entity",
    "crates/rave-api-iam",
    "crates/rave-core-common",
    "crates/rave-core-asset",
    "crates/rave-core-database",
]
