on: [push]

name: CD

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p rave-app-backend --release

      - name: push binary to dev instance
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ec2-52-47-32-158.eu-west-3.compute.amazonaws.com
          username: ubuntu
          key: "${{ secrets.SSH_PRIVATE_KEY_DEV_INSTANCE }}"
          port: 22
          source: "./target/release/rave-app-backend"
          target: /home/ubuntu/

      - name: restart dev service
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ec2-52-47-32-158.eu-west-3.compute.amazonaws.com
          username: ubuntu
          key: "${{ secrets.SSH_PRIVATE_KEY_DEV_INSTANCE }}"
          port: 22
          script: whoami